# Disable the newline at the start of the prompt
#add_newline = false

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€"

[directory]
style = "#ba55d3"
truncation_length = 0
truncate_to_repo = false

[dotnet]
symbol = "ğŸ¥… "
style = "green"
heuristic = false

[env_var]
disabled = false

[git_commit]
disabled = false
commit_hash_length = 4
